### ISSUE TITLE
Property 'on' does not exist on type 'FFmpeg'.ts(2339)

### ISSUE THREAD

**Issue by bropat** [mekwall/ffmpeggy#14]
Hi,

I tried your example code, but I get the following error:

`The property 'on' does not exist for the type 'FFmpeg'.ts(2339)`

Example code:

```typescript
import { FFmpeg } from "ffmpeggy";

new FFmpeg({
    autorun: true,
    input: "input.mp4",
    output: "output.mkv",
    outputOptions: ["-c:v h264"],
  })
  .on("start", (args) => {
    console.log(`ffmpeg was started with these args:`, args);
  })
  .on("progress", (event) => {
    console.log(`${event.progress}%`);
  })
  .on("error", (error) => {
    console.error(`Something went wrong =(`, error);
  })
  .on("done", (outputFile) => {
    console.log(`Done =)`);
  });
```

Can you maybe help me? :)

**Comment by mekwall** [comment]
Oh, `typed-emitter` was set as a dev dependency. I just pushed a fix that moves it to dependencies. It should work with `v1.0.3`. Thanks for the report!
